= Bazel Kotlin Rules on JDK16
:Author:    Oliver Eikemeier
:Email:     <eikemeier@fillmore-labs.com>
:Date:      2021-11
:Revision:  v0.2
:toc: macro
:prewrap!:

toc::[]

== Discussion

Kotlin compilation failes on JDK16.

[source,shell]
bazel run //:main

terminates with a compilation error:

....
java.lang.IllegalAccessException: class io.bazel.kotlin.builder.toolchain.KotlinToolchain$JDepsInvoker cannot access class com.sun.tools.jdeps.Main (in module jdk.jdeps) because module jdk.jdeps does not export com.sun.tools.jdeps to unnamed module @90a6e7f
....

if we comment out `build --tool_java_runtime_version` in `link:.bazelrc[.bazelrc]`, compilation
works.

Bazel: 5.0rc2

Kotlin Rules: 1.5.0 (Beta 4)

[bibliography]
== References

* [[[GH-527]]] Bazel Kotlin Rules https://github.com/bazelbuild/rules_kotlin/pull/527[issue #527]:
_“Reduce illegal reflective operation warnings when compiling code”_
* [[[KT-43704]]] JetBrains Kotlin https://youtrack.jetbrains.com/issue/KT-43704[issue KT-43704]:
_“Illegal reflective access by com.intellij.util.ReflectionUtil to method
java.util.ResourceBundle.setParent(java.util.ResourceBundle)”_
* [[[KT-47152]]] JetBrains Kotlin https://youtrack.jetbrains.com/issue/KT-47152[issue KT-47152]:
_“Incremental Compilation with Kotlin compile daemon and JDK 17 fails with IllegalAccessException”_
* [[[KT-45689]]] JetBrains Kotlin https://youtrack.jetbrains.com/issue/KT-45689[issue KT-45689]:
_“JDK-16: kotlin-maven-plugin fails with 'IllegalAccessError: class
com.intellij.util.io.FileChannelUtil' when using incremental compilation”_
