load("@io_bazel_rules_kotlin//kotlin:jvm.bzl", "kt_jvm_binary")

kt_jvm_binary(
    name = "example",
    srcs = glob(["*.kt"]),
    main_class = "com.example.MainKt",
    visibility = ["//visibility:public"],
)
